<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$quickSearchUrl = $escaper->escapeUrl($helper->getSuggestUrl());
?>
<div data-block="dropdown" class="minicart-wrapper">
    <span data-trigger="trigger">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clip-path="url(#clip0_11909_951)">
                <rect width="24" height="24" fill="white"/>
                <circle cx="11.1953" cy="10.1924" r="6.5" transform="rotate(45 11.1953 10.1924)" stroke="black"/>
                <rect x="16.0234" y="14.3145" width="7" height="1" rx="0.5" transform="rotate(45 16.0234 14.3145)" fill="black"/>
            </g>
            <defs>
                <clipPath id="clip0_11909_951">
                    <rect width="24" height="24" fill="white"/>
                </clipPath>
            </defs>
        </svg>
    </span>
</div>
<div class="block block-minicart"
     data-mage-init='{
        "dropdownDialog": {
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "timeout": 2000,
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "autoOpen": false,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": []
        }
     }' style="display: none;">
    <div id="minicart-content-wrapper">
        <div class="block block-content block-search">
            <form class="form minisearch" id="search_mini_form"
                action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <?php  if (!empty($queryParams = $additionalSearchFormData->getFormData())): ?>
                    <?php foreach ($queryParams as $param): ?>
                        <input type="hidden" name="<?= $escaper->escapeHtmlAttr($param['name']) ?>"
                            value="<?= $escaper->escapeHtmlAttr($param['value']) ?>"/>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                            data-mage-init='{
                                "quickSearch": {
                                    "formSelector": "#search_mini_form",
                                    "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                    "destinationSelector": "#search_autocomplete",
                                    "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                                }
                            }'
                            type="text"
                            name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                            value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                            placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
                            class="input-text"
                            maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                            role="combobox"
                            aria-haspopup="false"
                            aria-autocomplete="both"
                            autocomplete="off"
                            aria-expanded="false"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?= $escaper->escapeHtml(__('Search')) ?>"
                            class="action search"
                            aria-label="Search"
                    >
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>





